// ------------------ 1. Styled Text PDF ------------------
function makeStyledPDF() {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF("p", "mm", "a4");

    const text = document.getElementById("text").value;

    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.setTextColor(40, 80, 200);
    doc.text("✨ Custom Styled PDF", 10, 15);

    // Line under header
    doc.setDrawColor(40, 80, 200);
    doc.setLineWidth(1);
    doc.line(10, 20, 200, 20);

    // Body text
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(40, 40, 40);

    let lines = doc.splitTextToSize(text, 180);
    doc.text(lines, 10, 30);

    // Footer + page number
    doc.setFontSize(10);
    doc.text("Generated by Your PDF Tool", 10, 290);
    doc.text("Page 1", 190, 290);

    doc.save("styled_text.pdf");
}



// ------------------ 2. Styled HTML to PDF ------------------
function convertStyledHTML() {
    let element = document.getElementById("content");

    html2pdf().set({
        margin: 15,
        filename: "styled_html.pdf",
        image: { type: "jpeg", quality: 0.98 },
        html2canvas: { scale: 2 },
        jsPDF: { unit: "mm", format: "a4", orientation: "portrait" }
    })
    .from(element)
    .save();
}




// ------------ 3. Image → PDF --------------
// function imageToPDF() {
//     const file = document.getElementById("imgUpload").files[0];
//     if (!file) { alert("Please upload an image."); return; }

//     const reader = new FileReader();
//     reader.onload = function (e) {

//         const { jsPDF } = window.jspdf;
//         const doc = new jsPDF();

//         doc.addImage(e.target.result, "JPEG", 10, 10, 180, 150);
//         doc.save("image.pdf");
//     };

//     reader.readAsDataURL(file);
// }



// ------------ 4. Multi-page Text PDF --------------
// function makeMultiPagePDF() {
//     const { jsPDF } = window.jspdf;
//     const doc = new jsPDF();

//     let text = document.getElementById("multiText").value;

//     let lines = doc.splitTextToSize(text, 180);
//     let y = 10;

//     lines.forEach(line => {
//         if (y > 280) { 
//             doc.addPage(); 
//             y = 10; 
//         }
//         doc.text(line, 10, y);
//         y += 7;
//     });

//     doc.save("multi_page_text.pdf");
// }
